// <auto-generated />
using CardosoRestaurante.Services.ProdutoAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CardosoRestaurante.Services.ProdutoAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CardosoRestaurante.Services.ProdutoAPI.Models.Produto", b =>
                {
                    b.Property<int>("ProdutoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProdutoId"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagemUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Porcao")
                        .HasColumnType("int");

                    b.Property<double>("Preco")
                        .HasColumnType("float");

                    b.HasKey("ProdutoId");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            ProdutoId = 1,
                            Categoria = "Entradas",
                            Descricao = "Salada de alface, tomate, cenoura, pepino, cebola, ovo cozido, atum, milho, azeitonas e molho de iogurte.",
                            ImagemUrl = "https://imagedelivery.net/DDZ73aQyRCLNE8HUNFSEug/businesses/pt510587070/items/mikado-salad.jpg/thumb",
                            Nome = "Salada Mikado",
                            Porcao = 1,
                            Preco = 7.9900000000000002
                        },
                        new
                        {
                            ProdutoId = 2,
                            Categoria = "Entradas",
                            Descricao = "Mini crepes estaladiços recheados de legumes variados, acompanhado de molho agridoce.",
                            ImagemUrl = "https://imagedelivery.net/DDZ73aQyRCLNE8HUNFSEug/businesses/pt510587070/items/mini-vegetable-crepes.jpg/thumb",
                            Nome = "Mini Crepes de Legumes",
                            Porcao = 6,
                            Preco = 5.0
                        },
                        new
                        {
                            ProdutoId = 3,
                            Categoria = "Entradas",
                            Descricao = "Camarões panados em panko com molho agridoce",
                            ImagemUrl = "https://imagedelivery.net/DDZ73aQyRCLNE8HUNFSEug/businesses/pt510587070/items/fried-shrimp.jpg/details",
                            Nome = "Camarão Panado",
                            Porcao = 6,
                            Preco = 6.5
                        },
                        new
                        {
                            ProdutoId = 4,
                            Categoria = "Sopas",
                            Descricao = "Sopa de legumes variados.",
                            ImagemUrl = "https://j6t2y8j5.rocketcdn.me/wp-content/uploads/2021/02/como-fazer-sopa-de-legumes-historia-do-prato-receitas-deliciosas.jpg",
                            Nome = "Sopa de Legumes",
                            Porcao = 1,
                            Preco = 3.5
                        },
                        new
                        {
                            ProdutoId = 5,
                            Categoria = "Sopas",
                            Descricao = "Sopa de peixe com peixe variado.",
                            ImagemUrl = "https://www.becel.com/pt-pt/-/media/Project/Upfield/Brands/Becel-NL/Becel-PT/Assets/Recipes/94adcfb4-e9b6-4738-8037-76d905e8a40c.jpg?rev=db87e9aadfb74e87a12dfec4acc944b6",
                            Nome = "Sopa de Peixe",
                            Porcao = 1,
                            Preco = 4.5
                        },
                        new
                        {
                            ProdutoId = 10,
                            Categoria = "Sushi",
                            Descricao = "Sushi em forma de cone para se comer à mão recheado de salmão, abacate, manga e queijo creme.",
                            ImagemUrl = "https://imagedelivery.net/DDZ73aQyRCLNE8HUNFSEug/businesses/pt510587070/items/salmon-temaki.jpg/details",
                            Nome = "Temaki de Salmão",
                            Porcao = 1,
                            Preco = 6.0
                        },
                        new
                        {
                            ProdutoId = 11,
                            Categoria = "Sushi",
                            Descricao = "Sushi em forma de cone para se comer à mão recheado de camarão panado, queijo creme e molho teriyaki.",
                            ImagemUrl = "https://imagedelivery.net/DDZ73aQyRCLNE8HUNFSEug/businesses/pt510587070/items/crispy-ebi-temaki.jpg/details",
                            Nome = "Temaki Camarão Crocante",
                            Porcao = 1,
                            Preco = 6.0
                        },
                        new
                        {
                            ProdutoId = 12,
                            Categoria = "Sushi",
                            Descricao = "Rolo de sushi invertido panado em panko, recheado com pasta de peixe e maionese, com molho teriyaki.",
                            ImagemUrl = "https://imagedelivery.net/DDZ73aQyRCLNE8HUNFSEug/businesses/pt510587070/items/hot-uramaki.jpg/details",
                            Nome = "Hot Uramaki",
                            Porcao = 4,
                            Preco = 3.5
                        },
                        new
                        {
                            ProdutoId = 13,
                            Categoria = "Sushi",
                            Descricao = "Variedade de legumes e cogumelos salteados na wok.",
                            ImagemUrl = "https://imagedelivery.net/DDZ73aQyRCLNE8HUNFSEug/businesses/pt510587070/items/sauteed-vegetables.jpg/details",
                            Nome = "Legumes Salteados",
                            Porcao = 1,
                            Preco = 4.5
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
