// <auto-generated />
using CardosoRestaurante.Services.Carrinho.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CardosoRestaurante.Services.Carrinho.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CardosoRestaurante.Services.Carrinho.API.Models.CarrinhoDetalhes", b =>
                {
                    b.Property<int>("CarrinhoDetalhesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CarrinhoDetalhesId"));

                    b.Property<int>("CarrinhoInfoId")
                        .HasColumnType("int");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("CarrinhoDetalhesId");

                    b.HasIndex("CarrinhoInfoId");

                    b.ToTable("CarrinhoDetalhes");
                });

            modelBuilder.Entity("CardosoRestaurante.Services.Carrinho.API.Models.CarrinhoInfo", b =>
                {
                    b.Property<int>("CarrinhoInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CarrinhoInfoId"));

                    b.Property<string>("CupaoCodigo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CarrinhoInfoId");

                    b.ToTable("CarrinhoInfos");
                });

            modelBuilder.Entity("CardosoRestaurante.Services.Carrinho.API.Models.CarrinhoDetalhes", b =>
                {
                    b.HasOne("CardosoRestaurante.Services.Carrinho.API.Models.CarrinhoInfo", "CarrinhoInfo")
                        .WithMany()
                        .HasForeignKey("CarrinhoInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarrinhoInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
